8.3
DonShpil/rtacademy-homework pull request #3
Opened 2022-07-23 20:40 UTC by DonShpil

2022-08-03 10:02 UTC, roman-rtacademy commented on 08/8.1/8.1.sql
> +CREATE TABLE users (
Чому в тебе ці файли у цьому PR?

2022-08-03 10:04 UTC, roman-rtacademy requested changes

2022-08-03 10:04 UTC, roman-rtacademy commented on 08/8.2/8.2.sql
> +create type gender_sex as enum  ('male','female','other'
Чому в тебе ці файли у цьому PR?

2022-08-03 10:04 UTC, roman-rtacademy commented on 08/8.3/8.3.1.sql
> +                       email varchar(255) not null unique ,
email великими і маленькими літерами будуть вважатися уніканими або ні?

2022-08-13 15:42 UTC, DonShpil commented on 08/8.3/8.3.1.sql
> +                       email varchar(255) not null unique ,
нет они будут разные

2022-08-13 16:16 UTC, DonShpil commented on 08/8.1/8.1.sql
> +CREATE TABLE users (
не знаю может не правильно что делаю?

2022-09-03 17:32 UTC, roman-rtacademy commented on 08/8.1/8.1.sql
> +CREATE TABLE users (
Я до того що вони в тебе вже змерджені з main/master. Онови цю гілку з main/master.

2022-09-03 17:33 UTC, roman-rtacademy commented on 08/8.3/8.3.1.sql
> +                       email varchar(255) not null unique ,
Так в цьому і проблема що в тебе будуть два записи з одним і тим же email, але в різному регістрі.

2022-09-03 17:33 UTC, roman-rtacademy requested changes
Нагадую про мої коментарі до цього PR.

2022-09-03 17:34 UTC, merged